[mypy]
python_version = 3.13
warn_return_any = false
warn_unused_configs = true
warn_unused_ignores = false
disallow_untyped_defs = false
disallow_incomplete_defs = false
check_untyped_defs = true
disallow_untyped_decorators = false
show_error_codes = true
ignore_missing_imports = true

[mypy-tests.*]
ignore_errors = true

[mypy-tests]
ignore_errors = true

[mypy-fu7ur3pr00f.agents.tools.market]
ignore_errors = true

[mypy-fu7ur3pr00f.chat.client]
ignore_errors = true

[mypy-fu7ur3pr00f.cli]
ignore_errors = true
